"""add universities and careers
Revision ID: 687ba0a6de5a
Revises: de8475722bc9
Create Date: 2026-01-07 03:34:37.148832
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '687ba0a6de5a'
down_revision = 'de8475722bc9'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
