"""extend user with location and gamification
Revision ID: b4dfa1939863
Revises: 687ba0a6de5a
Create Date: 2026-01-07 03:40:34.472117
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b4dfa1939863'
down_revision = '687ba0a6de5a'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('province_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('region_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.Enum('masculino', 'femenino', 'otro', 'prefiero_no_decir', name='gender'), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('preferred_theme', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('preferred_lang', sa.String(length=5), nullable=True))
    op.add_column('users', sa.Column('accepts_terms', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('accepts_privacy', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('current_level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('xp_total', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('streak_days', sa.Integer(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'users', 'regions', ['region_id'], ['id'])
    op.create_foreign_key(None, 'users', 'provinces', ['province_id'], ['id'])
    op.create_foreign_key(None, 'users', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'streak_days')
    op.drop_column('users', 'xp_total')
    op.drop_column('users', 'current_level')
    op.drop_column('users', 'accepts_privacy')
    op.drop_column('users', 'accepts_terms')
    op.drop_column('users', 'preferred_lang')
    op.drop_column('users', 'preferred_theme')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'region_id')
    op.drop_column('users', 'province_id')
    op.drop_column('users', 'city_id')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
